"""Where spend lands on /usage, and whether the page's sentences about it are true.

The bug these guard against was not a wrong number. Every figure on the page was
right; the sentence under them said seven successful re-teaches were generation runs
that had failed, because re-teaching calls were recorded with no course and the only
copy for "no course" was about failure. So most of what is asserted here is prose:
which group a call lands in, and whether the sentence printed under that group is
true of the calls actually in it.

Every LLM call goes through a stub provider. Nothing here reaches a real API.
"""

import json
from datetime import UTC, datetime, timedelta
from uuid import uuid4

from sqlalchemy import create_engine, event
from sqlalchemy.orm import sessionmaker

from app import days, fsrs, generation, main, models, remediation, review, tutor
from app.concepts import normalize_concept
from app.db import Base, SessionLocal
from app.llm.base import LLMCallError, LLMResult
from app.llm.fake_provider import FakeProvider

# --------------------------------------------------------------------------
# Stub providers
# --------------------------------------------------------------------------


class ReteachProvider:
    """Returns a well-formed remedial note, with exact token counts and no price."""

    name = "fake"
    model = "reteach-model"
    is_paid = False

    def __init__(self):
        self.calls = 0

    def generate(self, system: str, prompt: str, max_tokens: int = 64000):
        self.calls += 1
        text = json.dumps(
            {
                "restatement": "The idea again, in plainer words.",
                "worked_example": "Step one, then step two, and that is why it follows.",
            }
        )
        return LLMResult(text=text, input_tokens=120, output_tokens=60)


class TutorTurnProvider:
    """Returns a well-formed tutor reply, with exact token counts and no price."""

    name = "fake"
    model = "tutor-model"
    is_paid = False

    def __init__(self):
        self.calls = 0

    def generate(self, system: str, prompt: str, max_tokens: int = 64000):
        self.calls += 1
        text = json.dumps(
            {
                "answer": "The idea again, grounded in your course.",
                "check": "What does it take in, and what does it give back?",
            }
        )
        return LLMResult(text=text, input_tokens=110, output_tokens=55)


class FailingTutorProvider:
    """A tutor call that dies in transport, after the meter has already been built."""

    name = "fake"
    model = "tutor-model"
    is_paid = False

    def __init__(self):
        self.calls = 0

    def generate(self, system: str, prompt: str, max_tokens: int = 64000):
        self.calls += 1
        raise LLMCallError("simulated tutor failure", input_tokens=30, output_tokens=0)


class OutlineThenFails:
    """A generation run that dies on the lesson stage after paying for the outline."""

    name = "anthropic"
    model = "claude-opus-5"
    is_paid = True

    def __init__(self):
        self.calls = 0

    def generate(self, system: str, prompt: str, max_tokens: int = 64000):
        self.calls += 1
        if self.calls == 1:
            text = json.dumps(
                {
                    "title": "Doomed Course",
                    "description": "Never reaches _save_course",
                    "modules": [
                        {"title": "Module 1", "lessons": [{"title": "Lesson A", "summary": "s"}]}
                    ],
                }
            )
            return LLMResult(text=text, input_tokens=100, output_tokens=50)
        raise LLMCallError("simulated mid-run failure", input_tokens=20, output_tokens=0)


class UnpricedPaidProvider:
    """A paid provider whose model id costs.PRICING has never heard of.

    Not a contrivance: a model released after that table was last updated looks exactly
    like this. Token counts are exact and the PRICE is the fallback, which is the case
    the approximate notice used to describe as a missing token count.
    """

    name = "anthropic"
    model = "vendor-model-absent-from-the-pricing-table"
    is_paid = True

    def __init__(self):
        self.calls = 0

    def generate(self, system: str, prompt: str, max_tokens: int = 64000):
        self.calls += 1
        if "curriculum designer" in system:
            text = json.dumps(
                {
                    "title": "Unpriced Course",
                    "description": "Generated by a model with no pricing entry",
                    "modules": [
                        {"title": "Module 1", "lessons": [{"title": "Lesson A", "summary": "s"}]}
                    ],
                }
            )
        else:
            text = json.dumps(
                {
                    "content": "# Lesson\nStub content",
                    "concepts": ["concept-1"],
                    "quiz": [
                        {
                            "question": "Q?",
                            "kind": "short",
                            "options": [],
                            "answer": "a",
                            "concept": "concept-1",
                        }
                    ],
                }
            )
        return LLMResult(text=text, input_tokens=1000, output_tokens=500)


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------


def _lesson_teaching(label: str, position: int) -> models.Lesson:
    lesson = models.Lesson(
        title=f"Lesson {position} on {label}",
        position=position,
        content=f"{label} is the idea under test, explained at some length.",
        concepts=[label],
    )
    lesson.quiz_items.append(
        models.QuizItem(
            question=f"What is {label}? (lesson {position})",
            kind="short",
            options=[],
            answer="the idea under test",
            concept=label,
        )
    )
    return lesson


def _seed_struggling_concept(
    course_count: int, lessons_per_course: list[int] | None = None
) -> tuple[int, str, list[int]]:
    """One concept taught by `course_count` courses, rated badly enough to be flagged.

    lessons_per_course says how many lessons of each course teach it, defaulting to one
    each. More than one matters because MAX_LESSONS trims what the prompt is grounded
    in, and attribution must not be trimmed with it.

    The label is unique per call because concept keys are global and the test database
    is shared across the suite: a fixed label would let one test's courses decide
    whether another test's concept can be traced to exactly one course.
    """
    counts = lessons_per_course or [1] * course_count
    assert len(counts) == course_count
    label = f"Concept {uuid4().hex[:8]}"
    key = normalize_concept(label)
    course_ids: list[int] = []
    session = SessionLocal()
    try:
        for index, lesson_count in enumerate(counts):
            course = models.Course(title=f"Course {index} teaching {label}", description="")
            module = models.Module(title="Module 1", position=0)
            for position in range(lesson_count):
                module.lessons.append(_lesson_teaching(label, position))
            course.modules.append(module)
            session.add(course)
            session.commit()
            course_ids.append(course.id)

        # Two lapses inside review.ATTENTION_WINDOW is exactly what needs_attention
        # triggers on, and that trigger is the only way to reach the endpoint.
        moment = datetime.now(UTC).replace(tzinfo=None) - timedelta(days=4)
        for rating in (fsrs.AGAIN, fsrs.AGAIN, fsrs.GOOD):
            review.record_review(session, key, label, rating, now=moment)
            moment += timedelta(days=1)
        session.commit()
        card = review.get_card(session, key)
        # SQLite hands a deleted row's id to the next insert, and some tests in this
        # suite delete review cards, so a brand new card can arrive already carrying
        # another test's remedial notes and answer the endpoint with their cooldown.
        # The app itself never deletes a card, so this is test hygiene, not a guard
        # against anything production does.
        session.query(models.RemediationNote).filter(
            models.RemediationNote.card_id == card.id
        ).delete()
        session.commit()
        return card.id, key, course_ids
    finally:
        session.close()


def _seed_taught_concept(
    course_count: int, lessons_per_course: list[int] | None = None
) -> tuple[str, list[int]]:
    """One concept taught by `course_count` courses, with no review card at all.

    No card on purpose, unlike _seed_struggling_concept. The tutor neither looks one up
    nor needs one, so seeding a card here would quietly make these tests depend on
    something the endpoint never reads.

    The label is unique per call because concept keys are global and the test database is
    shared across the suite: a fixed label would let one test's courses decide whether
    another test's concept can be traced to exactly one course.
    """
    counts = lessons_per_course or [1] * course_count
    assert len(counts) == course_count
    label = f"Concept {uuid4().hex[:8]}"
    key = normalize_concept(label)
    course_ids: list[int] = []
    session = SessionLocal()
    try:
        for index, lesson_count in enumerate(counts):
            course = models.Course(title=f"Course {index} teaching {label}", description="")
            module = models.Module(title="Module 1", position=0)
            for position in range(lesson_count):
                module.lessons.append(_lesson_teaching(label, position))
            course.modules.append(module)
            session.add(course)
            session.commit()
            course_ids.append(course.id)
        return key, course_ids
    finally:
        session.close()


def _ask_tutor(client, concept_key: str):
    """One tutor turn, with the day's cap cleared out of the way first.

    Clearing is test hygiene against a shared database, not a guard against anything the
    app does. The cap counts every learner turn written today across every concept, and
    test_tutor_endpoints.py deliberately seeds runs of them, so a turn here could
    otherwise be refused for a reason that has nothing to do with attribution.
    """
    day_start, day_end = days.day_bounds()
    session = SessionLocal()
    try:
        session.query(models.TutorMessage).filter(
            models.TutorMessage.created_at >= day_start
        ).filter(models.TutorMessage.created_at < day_end).delete()
        session.commit()
    finally:
        session.close()
    return client.post(
        "/tutor/messages",
        json={"concept_key": concept_key, "message": "I do not follow this part"},
    )


def _newest_tutor_call() -> models.LlmCall:
    session = SessionLocal()
    try:
        return (
            session.query(models.LlmCall)
            .filter(models.LlmCall.stage == tutor.TUTOR_STAGE)
            .order_by(models.LlmCall.id.desc())
            .first()
        )
    finally:
        session.close()


def _newest_remediation_call() -> models.LlmCall:
    session = SessionLocal()
    try:
        return (
            session.query(models.LlmCall)
            .filter(models.LlmCall.stage == remediation.REMEDIATION_STAGE)
            .order_by(models.LlmCall.id.desc())
            .first()
        )
    finally:
        session.close()


def _group_of(groups: list[dict], group: str) -> dict | None:
    return next((row for row in groups if row["group"] == group), None)


def _course_group_of(groups: list[dict], course_id: int) -> dict | None:
    return next((row for row in groups if row["course_id"] == course_id), None)


def _group(usage: dict, group: str) -> dict | None:
    return _group_of(usage["per_course"], group)


def _course_group(usage: dict, course_id: int) -> dict | None:
    return _course_group_of(usage["per_course"], course_id)


def _calls_in(row: dict | None) -> int:
    return 0 if row is None else row["calls"]


def _isolated_session():
    """A private database, so a test can assert about the whole llm_calls table.

    The suite shares one SQLite file and every test adds rows to it, which is fine for
    counting deltas but not for "is anything in here approximate", where the answer
    has to be about the rows this test wrote and nothing else.
    """
    engine = create_engine("sqlite://")
    Base.metadata.create_all(engine)
    return sessionmaker(bind=engine)()


def _record_call(session, **overrides) -> None:
    row = {
        "run_id": "r",
        "provider": "anthropic",
        "model": "claude-opus-5",
        "stage": "lesson",
        "course_id": None,
        "input_tokens": 100,
        "output_tokens": 50,
        "estimated_cost_usd": 0.001,
        "approximate": False,
    }
    session.add(models.LlmCall(**(row | overrides)))
    session.commit()


# --------------------------------------------------------------------------
# Where a re-teaching call's spend lands
# --------------------------------------------------------------------------


def test_reteach_is_charged_to_the_one_course_that_teaches_the_concept(client, monkeypatch):
    """The learner looks for re-teaching spend under the course they were re-taught."""
    provider = ReteachProvider()
    monkeypatch.setattr(main, "get_provider", lambda: provider)
    card_id, _, (course_id,) = _seed_struggling_concept(1)

    # Counted before, because the group is a total over the whole database and other
    # tests legitimately put their own re-teaches in it. What this test claims is that
    # ITS call did not land there, which is a delta, not an absence.
    unattributed_before = _calls_in(_group(client.get("/usage").json(), "remediation"))

    assert client.post(f"/review/cards/{card_id}/remediation").status_code == 200
    assert provider.calls == 1

    assert _newest_remediation_call().course_id == course_id

    usage = client.get("/usage").json()
    charged = _course_group(usage, course_id)
    assert charged is not None, "the re-teach was not charged to its course"
    assert charged["group"] == "course"
    assert charged["calls"] == 1  # this course was never generated, only re-taught
    assert charged["label"] == charged["title"]
    assert charged["note"] is None  # a course row needs no explaining
    assert _calls_in(_group(usage, "remediation")) == unattributed_before


def test_reteach_across_two_courses_stays_unattributed_and_is_not_called_a_failure(
    client, monkeypatch
):
    """The defect from the other side: a concept two courses teach has no one owner.

    Naming either course would put a real dollar figure against a course that did not
    earn it, so the call stays unattributed. What must not happen is the page then
    reporting a re-teach the learner watched succeed as a run that failed.
    """
    provider = ReteachProvider()
    monkeypatch.setattr(main, "get_provider", lambda: provider)
    card_id, _, course_ids = _seed_struggling_concept(2)

    failed_before = _calls_in(_group(client.get("/usage").json(), "failed_run"))

    assert client.post(f"/review/cards/{card_id}/remediation").status_code == 200
    assert _newest_remediation_call().course_id is None

    usage = client.get("/usage").json()
    reteach = _group(usage, "remediation")
    assert reteach is not None
    assert reteach["course_id"] is None
    assert reteach["label"] == "Re-teaching (no single course)"
    assert reteach["note"] == main.GROUP_NOTES[main.GROUP_REMEDIATION]
    # The whole point: this call is not described as a generation that failed.
    assert "generation run" not in reteach["note"]
    assert "could not be tied to a single course" in reteach["note"]

    # It did not leak into the failed-run bucket, and neither course was charged.
    assert _calls_in(_group(usage, "failed_run")) == failed_before
    for course_id in course_ids:
        assert _course_group(usage, course_id) is None


def test_attribution_ignores_the_prompts_lesson_budget(client, monkeypatch):
    """Trimming attribution to MAX_LESSONS would charge one course for shared spend.

    Course A teaches the concept in MAX_LESSONS lessons and course B in one more, so
    the trimmed set sees only A and names it, while the whole set sees both and
    correctly names neither. This is what the teaching_lessons/trim_material split is
    for, and without this case every test still passes when attribution is trimmed.
    """
    provider = ReteachProvider()
    monkeypatch.setattr(main, "get_provider", lambda: provider)
    card_id, key, (course_a, _course_b) = _seed_struggling_concept(
        2, lessons_per_course=[remediation.MAX_LESSONS, 1]
    )

    session = SessionLocal()
    try:
        matches = remediation.teaching_lessons(session, key)
        assert len(matches) == remediation.MAX_LESSONS + 1
        # The trimmed set names a single course. That is the wrong answer, and it is
        # the answer attribution would give if it shared the prompt's budget.
        assert remediation.sole_course_id(session, matches[: remediation.MAX_LESSONS]) is not None
        assert remediation.sole_course_id(session, matches) is None
    finally:
        session.close()

    reteach = client.post(f"/review/cards/{card_id}/remediation")
    assert reteach.status_code == 200, reteach.json()
    assert _newest_remediation_call().course_id is None
    assert _course_group(client.get("/usage").json(), course_a) is None


def test_a_generation_run_that_really_failed_is_still_unattributed_because_it_failed(
    client, monkeypatch
):
    """Splitting re-teaching out must not cost "unattributed" its original meaning."""
    provider = OutlineThenFails()
    monkeypatch.setattr(main, "get_provider", lambda: provider)

    failed_before = _calls_in(_group(client.get("/usage").json(), "failed_run"))

    doomed = client.post("/courses/generate", json={"text": "Doomed source material."})
    assert doomed.status_code == 502
    assert provider.calls == 2

    failed = _group(client.get("/usage").json(), "failed_run")
    assert failed is not None
    assert failed["course_id"] is None
    assert failed["title"] is None
    assert failed["label"] == "Unattributed"
    assert failed["calls"] == failed_before + 2  # the outline, and the lesson that raised
    assert failed["note"] == main.GROUP_NOTES[main.GROUP_FAILED_RUN]
    assert "failed before its course could be saved" in failed["note"]


def test_only_generation_stages_are_covered_by_the_failed_run_sentence():
    """The failed-run sentence speaks for every stage that is not re-teaching or the tutor.

    True today because the generation pipeline writes the only other stages, and that
    is the assumption the whole grouping rests on. A stage recorded from somewhere new
    would silently inherit a sentence about a generation run that failed, which is the
    exact shape of the bug this file exists for, so the covered set is pinned here.
    """
    assert set(generation.STAGES) == {"outline", "lesson"}
    assert remediation.REMEDIATION_STAGE not in generation.STAGES
    assert tutor.TUTOR_STAGE not in generation.STAGES
    assert tutor.TUTOR_STAGE != remediation.REMEDIATION_STAGE
    for stage in generation.STAGES:
        assert main._unattributed_group(stage) == main.GROUP_FAILED_RUN
    assert main._unattributed_group(remediation.REMEDIATION_STAGE) == main.GROUP_REMEDIATION
    assert main._unattributed_group(tutor.TUTOR_STAGE) == main.GROUP_TUTOR


def test_every_stage_actually_recorded_is_one_the_page_can_explain(client, monkeypatch):
    """The constant above can be honoured and still be wrong about what gets written.

    Pinning STAGES only fires if someone edits STAGES. A stage passed straight to
    meter.generate() would never touch it, and would land in a group whose sentence
    was written about something else. So this reads the stages the app ACTUALLY
    recorded, after driving both the paths that record any.
    """
    monkeypatch.setattr(main, "get_provider", lambda: FakeProvider())
    assert client.post("/courses/generate", json={"text": "Whales breathe air."}).status_code == 200

    monkeypatch.setattr(main, "get_provider", lambda: ReteachProvider())
    card_id, _, _ = _seed_struggling_concept(1)
    assert client.post(f"/review/cards/{card_id}/remediation").status_code == 200

    monkeypatch.setattr(main, "get_provider", lambda: TutorTurnProvider())
    key, _ = _seed_taught_concept(1)
    assert _ask_tutor(client, key).status_code == 200

    session = SessionLocal()
    try:
        recorded = {stage for (stage,) in session.query(models.LlmCall.stage).distinct()}
    finally:
        session.close()

    explained = set(generation.STAGES) | {remediation.REMEDIATION_STAGE, tutor.TUTOR_STAGE}
    assert explained <= recorded, "the scenario above should exercise every known stage"
    assert recorded <= explained, f"stage with no /usage copy: {sorted(recorded - explained)}"


# --------------------------------------------------------------------------
# The calls recorded before anything attributed them
# --------------------------------------------------------------------------


def _legacy_reteach(session, label: str, course_count: int, wrote_a_note: bool) -> str:
    """A re-teaching call shaped the way one looked before attribution existed.

    course_id NULL on the llm_calls row, and a RemediationNote sharing its run_id,
    unless the call failed: a failed call wrote no note, which is what leaves its
    concept unrecoverable. Returns the run_id.
    """
    key = normalize_concept(label)
    for index in range(course_count):
        course = models.Course(title=f"Course {index} teaching {label}", description="")
        module = models.Module(title="Module 1", position=0)
        module.lessons.append(_lesson_teaching(label, 0))
        course.modules.append(module)
        session.add(course)
    session.commit()

    card = review.get_card(session, key)
    if card is None:
        card = models.ReviewCard(concept_key=key, concept_label=label)
        session.add(card)
        session.commit()

    run_id = uuid4().hex
    if wrote_a_note:
        session.add(
            models.RemediationNote(
                card_id=card.id,
                concept_key=key,
                concept_label=label,
                content="## In simpler terms\n\nx\n\n## Worked example\n\ny",
                run_id=run_id,
            )
        )
    _record_call(session, run_id=run_id, stage=remediation.REMEDIATION_STAGE, course_id=None)
    session.commit()
    return run_id


def _call_for_run(session, run_id: str) -> models.LlmCall:
    return session.query(models.LlmCall).filter(models.LlmCall.run_id == run_id).one()


def test_backfill_attributes_legacy_reteaches_that_one_course_explains():
    """QA's seven rows, given a second false sentence by the fix meant to help them.

    Before the backfill these group under "could not be charged to one course" while
    sole_course_id, on the same request, names the course. The page must not be able to
    contradict itself like that, and the data is what has to change.
    """
    session = _isolated_session()
    try:
        run_id = _legacy_reteach(session, "Bayes rule", course_count=1, wrote_a_note=True)
        course_id = session.query(models.Course).one().id

        # The state the reviewer found: attributable, and not attributed.
        assert _call_for_run(session, run_id).course_id is None
        assert _group_of(main._spend_groups(session), "remediation") is not None

        assert remediation.backfill_course_ids(session) == 1
        session.commit()

        assert _call_for_run(session, run_id).course_id == course_id
        groups = main._spend_groups(session)
        assert _group_of(groups, "remediation") is None
        assert _course_group_of(groups, course_id)["calls"] == 1
    finally:
        session.close()


def test_backfill_leaves_alone_what_it_cannot_honestly_name():
    """Three ways a re-teach ends up with no course, all of which the sentence covers.

    Several courses teach it; no course teaches it any more, its lessons having gone; or
    the call failed and so recorded no concept at all. remediation._sole answers None to
    the first two alike and nothing downstream can separate them.

    The sentence names these as examples rather than as the whole set, because the set
    does not close: the course id is decided once and never revisited, so any claim
    phrased in the present tense can be falsified by editing the courseware afterwards.
    A row charged while two courses taught the concept fits none of the three the moment
    one of those courses goes away.
    """
    session = _isolated_session()
    try:
        ambiguous = _legacy_reteach(session, "Gradient descent", 2, wrote_a_note=True)
        no_course = _legacy_reteach(session, "Bayes factor", 0, wrote_a_note=True)
        no_note = _legacy_reteach(session, "Chain rule", 1, wrote_a_note=False)

        assert remediation.backfill_course_ids(session) == 0
        session.commit()

        assert _call_for_run(session, ambiguous).course_id is None
        assert _call_for_run(session, no_course).course_id is None
        assert _call_for_run(session, no_note).course_id is None
        assert _group_of(main._spend_groups(session), "remediation")["calls"] == 3

        note = main.GROUP_NOTES[main.GROUP_REMEDIATION]
        # The two words that keep this sentence true under any later edit to the
        # courseware: the claim is about when the row was charged, and the reasons are
        # offered as examples. A closed list in the present tense cannot survive, since
        # the course id is decided once and never revisited.
        assert "at the time they were charged" in note
        assert "commonly because" in note
        assert "several courses teach the concept" in note
        assert "the lessons that taught it are gone" in note
        assert "failed before anything recorded which concept it was for" in note
    finally:
        session.close()


def test_the_no_course_reteach_is_a_succeeding_call_with_a_recorded_concept():
    """Pins what makes the third cause a third cause, rather than a shade of the others.

    Its note exists, so the call succeeded and the concept IS recorded, which rules out
    the failed-call clause. And no course teaches it, which rules out the several-courses
    clause. Only the middle clause is true of it, so removing that clause would leave the
    page asserting two things that are both false about this row.
    """
    session = _isolated_session()
    try:
        run_id = _legacy_reteach(session, "Bayes rule", course_count=0, wrote_a_note=True)

        note = (
            session.query(models.RemediationNote)
            .filter(models.RemediationNote.run_id == run_id)
            .one()
        )
        assert note.concept_key  # the call succeeded and recorded what it taught
        assert remediation.course_ids_by_concept(session).get(note.concept_key) is None
        matches = remediation.teaching_lessons(session, note.concept_key)
        assert remediation.sole_course_id(session, matches) is None

        assert remediation.backfill_course_ids(session) == 0
        session.commit()
        assert _call_for_run(session, run_id).course_id is None
    finally:
        session.close()


def test_backfill_never_rewrites_a_course_id_already_recorded():
    """The NULL filter is load-bearing on the real upgrade path, not a nicety.

    Anyone who ran the previous commit has rows attributed at call time. This runs a
    FIRST backfill, the only one that reaches the query at all, against a database
    holding one such row, and the recorded attribution has to survive it: re-deriving it
    from today's courseware is exactly what the docstring argues against. The earlier
    once-only test could never catch this, because its second call returns at the
    app_settings guard without running the query.
    """
    session = _isolated_session()
    try:
        settled = _legacy_reteach(session, "Prior odds", course_count=1, wrote_a_note=True)
        pending = _legacy_reteach(session, "Posterior odds", course_count=1, wrote_a_note=True)

        # Attributed already, and to a course that does not teach it, so any re-derivation
        # from the current courseware is visible rather than coincidentally identical.
        _call_for_run(session, settled).course_id = 999
        session.commit()

        assert remediation.backfill_course_ids(session) == 1
        session.commit()

        assert _call_for_run(session, settled).course_id == 999
        assert _call_for_run(session, pending).course_id is not None
    finally:
        session.close()


def test_backfill_runs_once_and_never_rewrites_an_attribution():
    """A NULL course id after this feature is a decision taken at call time.

    Re-deriving it later, from a database that has since gained or lost a course, would
    overwrite that decision with a different day's answer. So the backfill records that
    it ran, and a second call does nothing at all.
    """
    session = _isolated_session()
    try:
        run_id = _legacy_reteach(session, "Entropy", course_count=1, wrote_a_note=True)
        assert remediation.backfill_course_ids(session) == 1
        session.commit()
        attributed = _call_for_run(session, run_id).course_id
        assert attributed is not None
        assert session.get(models.AppSetting, remediation.BACKFILL_SETTING) is not None

        # A second course starts teaching the concept, which would make it ambiguous.
        _legacy_reteach(session, "Entropy", course_count=1, wrote_a_note=False)

        assert remediation.backfill_course_ids(session) == 0
        session.commit()
        assert _call_for_run(session, run_id).course_id == attributed
    finally:
        session.close()


def _backfill_query_count(concepts: int) -> int:
    """Statements issued by one backfill over `concepts` distinct re-taught concepts."""
    session = _isolated_session()
    try:
        for index in range(concepts):
            _legacy_reteach(session, f"Concept {index}", course_count=1, wrote_a_note=True)

        statements = 0

        def count(conn, cursor, statement, parameters, context, executemany):
            nonlocal statements
            statements += 1

        engine = session.get_bind()
        event.listen(engine, "before_cursor_execute", count)
        try:
            assert remediation.backfill_course_ids(session) == concepts
            session.commit()
        finally:
            event.remove(engine, "before_cursor_execute", count)
        return statements
    finally:
        session.close()


def test_backfill_reads_the_courseware_once_however_many_concepts():
    """The shape, not the clock: statements must not grow with the number of concepts.

    sole_course_id(teaching_lessons()) per concept reads every lesson once per concept,
    which is quadratic and measured at twenty seconds for 200 concepts over 4000 lessons,
    on a boot that is serving nobody. A timing assertion would be flaky on a loaded
    machine; the query count is the property that actually went wrong.
    """
    few = _backfill_query_count(2)
    many = _backfill_query_count(20)
    assert few == many, f"{many - few} extra statements for 18 more concepts"


def test_backfill_already_ran_against_the_shared_database(client):
    """Safe on an existing database, including the ordinary case of nothing to fix.

    The client fixture boots the app against the shared test database, so startup has
    already run the backfill there: it must have left its marker and no damage.
    """
    session = SessionLocal()
    try:
        assert session.get(models.AppSetting, remediation.BACKFILL_SETTING) is not None
        assert remediation.backfill_course_ids(session) == 0
    finally:
        session.close()


# --------------------------------------------------------------------------
# Which figure the "approximate" notice is actually about
# --------------------------------------------------------------------------


def test_approximate_notice_names_the_price_when_the_price_was_the_estimate():
    """QA's second finding: exact tokens, unpriced model, and the page blamed the tokens."""
    session = _isolated_session()
    try:
        _record_call(session, model="fake", approximate=True)
        assert main._approximation_causes(session) == (False, True)

        note = main.APPROXIMATE_NOTES[(False, True)]
        assert "pricing table" in note
        assert "token counts are exact" in note
        assert "missing an exact token count" not in note
    finally:
        session.close()


def test_approximate_notice_names_the_token_count_when_a_count_was_missing():
    session = _isolated_session()
    try:
        _record_call(session, output_tokens=None, approximate=True)
        assert main._approximation_causes(session) == (True, False)

        note = main.APPROXIMATE_NOTES[(True, False)]
        assert "missing an exact token count" in note
        assert "pricing table" not in note
    finally:
        session.close()


def test_approximate_notice_names_both_causes_when_both_happened():
    session = _isolated_session()
    try:
        _record_call(session, model="fake", approximate=True)
        _record_call(session, output_tokens=None, approximate=True)
        assert main._approximation_causes(session) == (True, True)

        note = main.APPROXIMATE_NOTES[(True, True)]
        assert "pricing table" in note
        assert "missing an exact token count" in note
    finally:
        session.close()


def test_one_call_can_carry_both_causes_at_once():
    """A single unpriced call that lost one of its two counts is both, not just tokens.

    The count it kept was still priced at a guessed rate, and a non-zero cost is what
    proves a rate was applied: an unpaid provider always records zero, and a paid call
    that lost BOTH counts prices zero tokens, so no rate reached the page either way.
    """
    session = _isolated_session()
    try:
        _record_call(session, model="fake", output_tokens=None, approximate=True)
        assert main._approximation_causes(session) == (True, True)
    finally:
        session.close()

    session = _isolated_session()
    try:
        # Both counts gone: the cost is zero whatever the rate, so no price is claimed.
        _record_call(
            session,
            model="fake",
            input_tokens=None,
            output_tokens=None,
            estimated_cost_usd=0.0,
            approximate=True,
        )
        assert main._approximation_causes(session) == (True, False)
    finally:
        session.close()


def test_no_approximate_notice_when_every_call_was_exact_and_priced():
    session = _isolated_session()
    try:
        _record_call(session)
        assert main._approximation_causes(session) == (False, False)
        assert main.APPROXIMATE_NOTES.get((False, False)) is None
    finally:
        session.close()


def test_usage_blames_the_pricing_table_not_the_token_counts(client, monkeypatch):
    """End to end, against the real endpoint, for the case QA hit.

    Scoped to the rows this run wrote, because the notice is a total over the whole
    database and this test only owns the calls it made.
    """
    monkeypatch.delenv("STUDYFORGE_COST_LIMIT_USD", raising=False)
    monkeypatch.setattr(main, "get_provider", lambda: UnpricedPaidProvider())

    generated = client.post("/courses/generate", json={"text": "Priced by no table."})
    assert generated.status_code == 200
    course_id = generated.json()["id"]

    # This run's own rows. Counting missing token counts across the whole table would
    # be a claim about every other test in the suite, and one of them adding a call
    # with no token count would fail this test without touching what it is about.
    session = SessionLocal()
    try:
        mine = (
            session.query(models.LlmCall).filter(models.LlmCall.course_id == course_id).all()
        )
    finally:
        session.close()
    assert mine, "the generation recorded no calls"
    for row in mine:
        assert row.input_tokens is not None and row.output_tokens is not None
        # Flagged approximate, with exact counts, which leaves the price as the only
        # thing that can have been estimated. That is the whole of QA's finding.
        assert row.approximate is True

    totals = client.get("/usage").json()["totals"]
    assert totals["approximate"] is True
    # Names the cause this run introduced. Whether it ALSO names a missing token count
    # depends on rows other tests wrote, so that half is not this test's to assert; the
    # exact note for each combination of causes is pinned on isolated sessions above.
    assert "pricing table" in totals["approximate_note"]


# --------------------------------------------------------------------------
# Where a tutor turn's spend lands
# --------------------------------------------------------------------------
#
# The tutor arrives on a page that already had this bug once. _unattributed_group sends
# every stage it does not recognize to the failed-run group, whose sentence tells the
# learner the spend came from a generation run that failed before its course could be
# saved. A tutor call that cannot be tied to one course has no course id, so without a
# branch of its own it lands there wearing that sentence: the identical defect that took
# four review rounds to fix for re-teaching, on the identical surface.
#
# Mutation-checked rather than read for plausibility. Deleting the tutor branch from
# main._unattributed_group turns the two tests below red, and the failure they print is
# the sentence itself.


def test_a_tutor_turn_is_charged_to_the_one_course_that_teaches_the_concept(client, monkeypatch):
    """The learner looks for tutor spend under the course they were asking about."""
    provider = TutorTurnProvider()
    monkeypatch.setattr(main, "get_provider", lambda: provider)
    key, (course_id,) = _seed_taught_concept(1)

    # Counted before, because the group is a total over the whole database and other
    # tests legitimately put their own turns in it. What this test claims is that ITS
    # call did not land there, which is a delta, not an absence.
    unattributed_before = _calls_in(_group(client.get("/usage").json(), "tutor"))

    answered = _ask_tutor(client, key)
    assert answered.status_code == 200, answered.json()
    assert provider.calls == 1

    assert _newest_tutor_call().course_id == course_id

    usage = client.get("/usage").json()
    charged = _course_group(usage, course_id)
    assert charged is not None, "the tutor turn was not charged to its course"
    assert charged["group"] == "course"
    assert charged["calls"] == 1  # this course was never generated, only asked about
    assert charged["label"] == charged["title"]
    assert charged["note"] is None  # a course row needs no explaining
    assert _calls_in(_group(usage, "tutor")) == unattributed_before


def test_a_tutor_turn_on_a_concept_two_courses_teach_is_charged_to_neither(client, monkeypatch):
    """AC 23 from the other side: a concept two courses teach has no one owner.

    Naming either would put a real dollar figure against a course that did not earn it,
    so the call stays unattributed rather than being charged to a coin flip.
    """
    provider = TutorTurnProvider()
    monkeypatch.setattr(main, "get_provider", lambda: provider)
    key, course_ids = _seed_taught_concept(2)

    assert _ask_tutor(client, key).status_code == 200
    assert _newest_tutor_call().course_id is None

    usage = client.get("/usage").json()
    for course_id in course_ids:
        assert _course_group(usage, course_id) is None


def test_tutor_attribution_ignores_the_prompts_lesson_budget(client, monkeypatch):
    """Charging from the trimmed material would name one course for shared spend.

    Course A teaches the concept in MAX_LESSONS lessons and course B in one more, so the
    trimmed set sees only A and names it, while the whole set sees both and correctly
    names neither. The endpoint reads teaching_lessons for attribution and tutor.context
    for the prompt precisely so these two answers cannot be confused, and without this
    case every other test still passes when they are.
    """
    provider = TutorTurnProvider()
    monkeypatch.setattr(main, "get_provider", lambda: provider)
    key, (course_a, _course_b) = _seed_taught_concept(
        2, lessons_per_course=[remediation.MAX_LESSONS, 1]
    )

    session = SessionLocal()
    try:
        matches = remediation.teaching_lessons(session, key)
        assert len(matches) == remediation.MAX_LESSONS + 1
        # The trimmed set names a single course. That is the wrong answer, and it is the
        # answer attribution would give if it shared the prompt's grounding budget.
        assert remediation.sole_course_id(session, matches[: remediation.MAX_LESSONS]) is not None
        assert remediation.sole_course_id(session, matches) is None
    finally:
        session.close()

    assert _ask_tutor(client, key).status_code == 200
    assert _newest_tutor_call().course_id is None
    assert _course_group(client.get("/usage").json(), course_a) is None


def test_usage_gives_the_tutor_its_own_copy_and_never_calls_it_a_failed_run(client, monkeypatch):
    """AC 24, and the reason this file exists.

    Three claims, and the middle one is the whole bug: the group is rendered, its sentence
    is about tutor calls rather than about failed generation runs, and no group anywhere
    on the page is left for the learner to guess at.
    """
    provider = TutorTurnProvider()
    monkeypatch.setattr(main, "get_provider", lambda: provider)
    key, _ = _seed_taught_concept(2)

    failed_before = _calls_in(_group(client.get("/usage").json(), "failed_run"))

    assert _ask_tutor(client, key).status_code == 200
    assert _newest_tutor_call().course_id is None

    usage = client.get("/usage").json()
    chat = _group(usage, "tutor")
    assert chat is not None, "the tutor turn was not given a group of its own"
    assert chat["course_id"] is None
    assert chat["title"] is None
    assert chat["label"] == "Tutor chat (no single course)"
    assert chat["note"] == main.GROUP_NOTES[main.GROUP_TUTOR]

    # The sentence the group was invented to avoid inheriting.
    assert "generation run" not in chat["note"]
    assert chat["note"] != main.GROUP_NOTES[main.GROUP_FAILED_RUN]
    assert chat["note"] != main.GROUP_NOTES[main.GROUP_REMEDIATION]
    assert _calls_in(_group(usage, "failed_run")) == failed_before

    # The two properties the re-teaching sentence took four rounds to arrive at, and the
    # reason each is load bearing is in the comment above main.GROUP_NOTES[GROUP_TUTOR].
    assert "at the time they were charged" in chat["note"]
    assert "commonly because" in chat["note"]
    # And it claims nothing about whether the call worked, because a failed tutor call
    # records its tokens and is grouped by exactly the same rule as one that succeeded.
    assert "Whether the call succeeded is a separate question" in chat["note"]

    # No unlabeled group: every row has a name, and every row that is not a course has a
    # sentence saying why it is not.
    for row in usage["per_course"]:
        assert row["label"], f"group with no label: {row}"
        assert row["group"] == main.GROUP_COURSE or row["note"], f"group with no copy: {row}"


def test_a_tutor_call_that_failed_is_still_charged_to_its_course(client, monkeypatch):
    """Why the tutor's sentence must NOT borrow the re-teaching clause about failure.

    A re-teaching call that failed wrote no note, so nothing recorded which concept it was
    for and it could never be attributed. A tutor call knows its course before it is made,
    so a failure is charged exactly like a success. Copying that clause across would have
    put a false sentence on this page, and this is the row that proves it false.
    """
    monkeypatch.setattr(main, "get_provider", lambda: FailingTutorProvider())
    key, (course_id,) = _seed_taught_concept(1)

    unattributed_before = _calls_in(_group(client.get("/usage").json(), "tutor"))

    assert _ask_tutor(client, key).status_code == 502

    # The tokens were spent, so the row exists, and it carries the course it was asked
    # about even though nothing came back.
    assert _newest_tutor_call().course_id == course_id

    usage = client.get("/usage").json()
    charged = _course_group(usage, course_id)
    assert charged is not None, "the failed tutor call was not charged to its course"
    assert charged["calls"] == 1
    # So it is NOT in the group whose sentence would have claimed it could not be tied to
    # a course. That is what makes the borrowed failure clause false here.
    assert _calls_in(_group(usage, "tutor")) == unattributed_before
