"""Where spend lands on /usage, and whether the page's sentences about it are true.

The bug these guard against was not a wrong number. Every figure on the page was
right; the sentence under them said seven successful re-teaches were generation runs
that had failed, because re-teaching calls were recorded with no course and the only
copy for "no course" was about failure. So most of what is asserted here is prose:
which group a call lands in, and whether the sentence printed under that group is
true of the calls actually in it.

Every LLM call goes through a stub provider. Nothing here reaches a real API.
"""

import json
from datetime import UTC, datetime, timedelta
from uuid import uuid4

from sqlalchemy import create_engine, or_
from sqlalchemy.orm import sessionmaker

from app import fsrs, generation, main, models, remediation, review
from app.concepts import normalize_concept
from app.db import Base, SessionLocal
from app.llm.base import LLMCallError, LLMResult

# --------------------------------------------------------------------------
# Stub providers
# --------------------------------------------------------------------------


class ReteachProvider:
    """Returns a well-formed remedial note, with exact token counts and no price."""

    name = "fake"
    model = "reteach-model"
    is_paid = False

    def __init__(self):
        self.calls = 0

    def generate(self, system: str, prompt: str, max_tokens: int = 64000):
        self.calls += 1
        text = json.dumps(
            {
                "restatement": "The idea again, in plainer words.",
                "worked_example": "Step one, then step two, and that is why it follows.",
            }
        )
        return LLMResult(text=text, input_tokens=120, output_tokens=60)


class OutlineThenFails:
    """A generation run that dies on the lesson stage after paying for the outline."""

    name = "anthropic"
    model = "claude-opus-5"
    is_paid = True

    def __init__(self):
        self.calls = 0

    def generate(self, system: str, prompt: str, max_tokens: int = 64000):
        self.calls += 1
        if self.calls == 1:
            text = json.dumps(
                {
                    "title": "Doomed Course",
                    "description": "Never reaches _save_course",
                    "modules": [
                        {"title": "Module 1", "lessons": [{"title": "Lesson A", "summary": "s"}]}
                    ],
                }
            )
            return LLMResult(text=text, input_tokens=100, output_tokens=50)
        raise LLMCallError("simulated mid-run failure", input_tokens=20, output_tokens=0)


class UnpricedPaidProvider:
    """A paid provider whose model id costs.PRICING has never heard of.

    Not a contrivance: a model released after that table was last updated looks exactly
    like this. Token counts are exact and the PRICE is the fallback, which is the case
    the approximate notice used to describe as a missing token count.
    """

    name = "anthropic"
    model = "vendor-model-absent-from-the-pricing-table"
    is_paid = True

    def __init__(self):
        self.calls = 0

    def generate(self, system: str, prompt: str, max_tokens: int = 64000):
        self.calls += 1
        if "curriculum designer" in system:
            text = json.dumps(
                {
                    "title": "Unpriced Course",
                    "description": "Generated by a model with no pricing entry",
                    "modules": [
                        {"title": "Module 1", "lessons": [{"title": "Lesson A", "summary": "s"}]}
                    ],
                }
            )
        else:
            text = json.dumps(
                {
                    "content": "# Lesson\nStub content",
                    "concepts": ["concept-1"],
                    "quiz": [
                        {
                            "question": "Q?",
                            "kind": "short",
                            "options": [],
                            "answer": "a",
                            "concept": "concept-1",
                        }
                    ],
                }
            )
        return LLMResult(text=text, input_tokens=1000, output_tokens=500)


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------


def _seed_struggling_concept(course_count: int) -> tuple[int, list[int]]:
    """One concept taught by `course_count` courses, rated badly enough to be flagged.

    The label is unique per call because concept keys are global and the test database
    is shared across the suite: a fixed label would let one test's courses decide
    whether another test's concept can be traced to exactly one course.
    """
    label = f"Concept {uuid4().hex[:8]}"
    key = normalize_concept(label)
    course_ids: list[int] = []
    session = SessionLocal()
    try:
        for index in range(course_count):
            course = models.Course(title=f"Course {index} teaching {label}", description="")
            module = models.Module(title="Module 1", position=0)
            lesson = models.Lesson(
                title=f"Lesson {index} on {label}",
                position=0,
                content=f"{label} is the idea under test, explained at some length.",
                concepts=[label],
            )
            lesson.quiz_items.append(
                models.QuizItem(
                    question=f"What is {label}?",
                    kind="short",
                    options=[],
                    answer="the idea under test",
                    concept=label,
                )
            )
            module.lessons.append(lesson)
            course.modules.append(module)
            session.add(course)
            session.commit()
            course_ids.append(course.id)

        # Two lapses inside review.ATTENTION_WINDOW is exactly what needs_attention
        # triggers on, and that trigger is the only way to reach the endpoint.
        moment = datetime.now(UTC).replace(tzinfo=None) - timedelta(days=4)
        for rating in (fsrs.AGAIN, fsrs.AGAIN, fsrs.GOOD):
            review.record_review(session, key, label, rating, now=moment)
            moment += timedelta(days=1)
        session.commit()
        return review.get_card(session, key).id, course_ids
    finally:
        session.close()


def _newest_remediation_call() -> models.LlmCall:
    session = SessionLocal()
    try:
        return (
            session.query(models.LlmCall)
            .filter(models.LlmCall.stage == remediation.REMEDIATION_STAGE)
            .order_by(models.LlmCall.id.desc())
            .first()
        )
    finally:
        session.close()


def _group(usage: dict, group: str) -> dict | None:
    return next((row for row in usage["per_course"] if row["group"] == group), None)


def _course_group(usage: dict, course_id: int) -> dict | None:
    return next((row for row in usage["per_course"] if row["course_id"] == course_id), None)


def _calls_in(row: dict | None) -> int:
    return 0 if row is None else row["calls"]


def _isolated_session():
    """A private database, so a test can assert about the whole llm_calls table.

    The suite shares one SQLite file and every test adds rows to it, which is fine for
    counting deltas but not for "is anything in here approximate", where the answer
    has to be about the rows this test wrote and nothing else.
    """
    engine = create_engine("sqlite://")
    Base.metadata.create_all(engine)
    return sessionmaker(bind=engine)()


def _record_call(session, **overrides) -> None:
    row = {
        "run_id": "r",
        "provider": "anthropic",
        "model": "claude-opus-5",
        "stage": "lesson",
        "course_id": None,
        "input_tokens": 100,
        "output_tokens": 50,
        "estimated_cost_usd": 0.001,
        "approximate": False,
    }
    session.add(models.LlmCall(**(row | overrides)))
    session.commit()


# --------------------------------------------------------------------------
# Where a re-teaching call's spend lands
# --------------------------------------------------------------------------


def test_reteach_is_charged_to_the_one_course_that_teaches_the_concept(client, monkeypatch):
    """The learner looks for re-teaching spend under the course they were re-taught."""
    provider = ReteachProvider()
    monkeypatch.setattr(main, "get_provider", lambda: provider)
    card_id, (course_id,) = _seed_struggling_concept(1)

    assert client.post(f"/review/cards/{card_id}/remediation").status_code == 200
    assert provider.calls == 1

    assert _newest_remediation_call().course_id == course_id

    usage = client.get("/usage").json()
    charged = _course_group(usage, course_id)
    assert charged is not None, "the re-teach was not charged to its course"
    assert charged["group"] == "course"
    assert charged["calls"] == 1  # this course was never generated, only re-taught
    assert charged["label"] == charged["title"]
    assert charged["note"] is None  # a course row needs no explaining
    assert _group(usage, "remediation") is None


def test_reteach_across_two_courses_stays_unattributed_and_is_not_called_a_failure(
    client, monkeypatch
):
    """The defect from the other side: a concept two courses teach has no one owner.

    Naming either course would put a real dollar figure against a course that did not
    earn it, so the call stays unattributed. What must not happen is the page then
    reporting a re-teach the learner watched succeed as a run that failed.
    """
    provider = ReteachProvider()
    monkeypatch.setattr(main, "get_provider", lambda: provider)
    card_id, course_ids = _seed_struggling_concept(2)

    failed_before = _calls_in(_group(client.get("/usage").json(), "failed_run"))

    assert client.post(f"/review/cards/{card_id}/remediation").status_code == 200
    assert _newest_remediation_call().course_id is None

    usage = client.get("/usage").json()
    reteach = _group(usage, "remediation")
    assert reteach is not None
    assert reteach["course_id"] is None
    assert reteach["label"] == "Re-teaching (no single course)"
    assert reteach["note"] == main.GROUP_NOTES[main.GROUP_REMEDIATION]
    # The whole point: this spend is not described as a failure of any kind.
    assert "fail" not in reteach["note"].lower()
    assert "no one course to charge them to" in reteach["note"]

    # It did not leak into the failed-run bucket, and neither course was charged.
    assert _calls_in(_group(usage, "failed_run")) == failed_before
    for course_id in course_ids:
        assert _course_group(usage, course_id) is None


def test_a_generation_run_that_really_failed_is_still_unattributed_because_it_failed(
    client, monkeypatch
):
    """Splitting re-teaching out must not cost "unattributed" its original meaning."""
    provider = OutlineThenFails()
    monkeypatch.setattr(main, "get_provider", lambda: provider)

    failed_before = _calls_in(_group(client.get("/usage").json(), "failed_run"))

    doomed = client.post("/courses/generate", json={"text": "Doomed source material."})
    assert doomed.status_code == 502
    assert provider.calls == 2

    failed = _group(client.get("/usage").json(), "failed_run")
    assert failed is not None
    assert failed["course_id"] is None
    assert failed["title"] is None
    assert failed["label"] == "Unattributed"
    assert failed["calls"] == failed_before + 2  # the outline, and the lesson that raised
    assert failed["note"] == main.GROUP_NOTES[main.GROUP_FAILED_RUN]
    assert "failed before its course could be saved" in failed["note"]


def test_only_generation_stages_are_covered_by_the_failed_run_sentence():
    """The failed-run sentence speaks for every stage that is not re-teaching.

    True today because the generation pipeline writes the only other stages, and that
    is the assumption the whole grouping rests on. A stage recorded from somewhere new
    would silently inherit a sentence about a generation run that failed, which is the
    exact shape of the bug this file exists for, so the covered set is pinned here.
    """
    assert set(generation.STAGES) == {"outline", "lesson"}
    assert remediation.REMEDIATION_STAGE not in generation.STAGES
    for stage in generation.STAGES:
        assert main._unattributed_group(stage) == main.GROUP_FAILED_RUN
    assert main._unattributed_group(remediation.REMEDIATION_STAGE) == main.GROUP_REMEDIATION


# --------------------------------------------------------------------------
# Which figure the "approximate" notice is actually about
# --------------------------------------------------------------------------


def test_approximate_notice_names_the_price_when_the_price_was_the_estimate():
    """QA's second finding: exact tokens, unpriced model, and the page blamed the tokens."""
    session = _isolated_session()
    try:
        _record_call(session, model="fake", approximate=True)
        assert main._approximation_causes(session) == (False, True)

        note = main.APPROXIMATE_NOTES[(False, True)]
        assert "pricing table" in note
        assert "token counts are exact" in note
        assert "missing an exact token count" not in note
    finally:
        session.close()


def test_approximate_notice_names_the_token_count_when_a_count_was_missing():
    session = _isolated_session()
    try:
        _record_call(session, output_tokens=None, approximate=True)
        assert main._approximation_causes(session) == (True, False)

        note = main.APPROXIMATE_NOTES[(True, False)]
        assert "missing an exact token count" in note
        assert "pricing table" not in note
    finally:
        session.close()


def test_approximate_notice_names_both_causes_when_both_happened():
    session = _isolated_session()
    try:
        _record_call(session, model="fake", approximate=True)
        _record_call(session, output_tokens=None, approximate=True)
        assert main._approximation_causes(session) == (True, True)

        note = main.APPROXIMATE_NOTES[(True, True)]
        assert "pricing table" in note
        assert "missing an exact token count" in note
    finally:
        session.close()


def test_no_approximate_notice_when_every_call_was_exact_and_priced():
    session = _isolated_session()
    try:
        _record_call(session)
        assert main._approximation_causes(session) == (False, False)
        assert main.APPROXIMATE_NOTES.get((False, False)) is None
    finally:
        session.close()


def test_usage_blames_the_pricing_table_not_the_token_counts(client, monkeypatch):
    """End to end, against the real endpoint, for the case QA hit.

    Left last in the file on purpose: it is the first thing in the suite to record an
    approximate call, and the shared test database keeps it for good.
    """
    monkeypatch.delenv("STUDYFORGE_COST_LIMIT_USD", raising=False)
    monkeypatch.setattr(main, "get_provider", lambda: UnpricedPaidProvider())

    generated = client.post("/courses/generate", json={"text": "Priced by no table."})
    assert generated.status_code == 200

    session = SessionLocal()
    try:
        missing_counts = (
            session.query(models.LlmCall)
            .filter(
                or_(
                    models.LlmCall.input_tokens.is_(None),
                    models.LlmCall.output_tokens.is_(None),
                )
            )
            .count()
        )
    finally:
        session.close()
    assert missing_counts == 0, "no recorded call is missing a token count"

    totals = client.get("/usage").json()["totals"]
    assert totals["approximate"] is True
    assert totals["approximate_note"] == main.APPROXIMATE_NOTES[(False, True)]
